### ISSUE TITLE
Monorepo leads to dev/build errors

### ISSUE THREAD

**Issue by GiorgosK** [YogliB/svelte-component-template#1059]
I have install the monorepo version but after `npm install` and `npm init` running `npm run dev` leads to following error 

```
$ pnpm dev

> hello@1.0.0 dev /home/projects/svelte-components
> rollup -c -w

rollup v2.35.1
bundles src/main.js → public/bundle.js...
[!] Error: Could not resolve './components' from src/App.svelte
Error: Could not resolve './components' from src/App.svelte
    at error (/home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at ModuleLoader.handleResolveId (/home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:18433:24)
    at /home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:18402:22
    at async Promise.all (index 1)
    at ModuleLoader.fetchStaticDependencies (/home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:18400:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:18377:9)
    at async Promise.all (index 0)
    at ModuleLoader.fetchStaticDependencies (/home/projects/svelte-components/node_modules/.pnpm/rollup@2.35.1/node_modules/rollup/dist/shared/rollup.js:18400:34)
    at async Promise.all (index 0)


[2021-01-27 18:15:55] waiting for changes...
```

example output is using `pnpm` but I have tried same process with `npm` and `yarn` but get same output

The regular version seems to work fine though

**Comment by YogliB** [comment]
My bad, I will state that I only got it to work properly with `yarn` (open an issue if it doesn't work properly).

Since I'm currently working on a new [CLI](https://github.com/YogliB/svelte-packagr) to simplify this whole thing, it'll probably take sometime before I'll add another monorepo template (`npm` & `pnpm`).

Note that I personally use `pnpm` on a regular basis, so it is a priority for me.
